### ISSUE TITLE
Cam-Connect: eMail bei Klingeln versenden

### ISSUE THREAD

**Issue by Woersty** [Woersty/LoxBerry-Plugin-cam-connect#1]
Feature-Idee: Email bei Klingeln versenden

**Comment by Woersty** [comment]
Warte auf eMail Schnittstelle vom Professor. :smiling_imp:

**Comment by mschlenstedt** [comment]
Ist fast fertig :-)

**Comment by mschlenstedt** [comment]
So, ist eingebaut. Bitte nach dem Pull noch folgendes ausführen:

mv /etc/ssmtp /etc/ssmtp.old
ln -s /opt/loxberry/system/ssmtp /etc/ssmtp

Nach der Einrichtung können über /usr/lib/sendmail dann Mails verschickt werden.

**Comment by Woersty** [comment]
Im Pull ist nichts neu? :confused:

**Comment by mschlenstedt** [comment]
Mmhh, ist aber drin: 

https://github.com/mschlenstedt/Loxberry/commit/8bc006c809cd99ad45abe6a754601520ff09b848
und
https://github.com/mschlenstedt/Loxberry/commit/8adcfb12d6fb0f6fdc3ea52eccd40cb9e9795237

**Comment by Woersty** [comment]
JETZT ist es auch da. Komisch alles.
Wo kommen denn die plugins plötzlich her?
Hab ich die aus Versehen gepsuht?
Na jedenfalls hab ich es jetzt.

**Comment by Woersty** [comment]
Achso https://github.com/mschlenstedt/Loxberry/issues/109 ist auch geklärt. Geht auch.

**Comment by mschlenstedt** [comment]
Mit den Plugins könnte auch ich gewesen sein - passiert mir auch ab und zu :-)

**Comment by Woersty** [comment]
Bin momentan ziemlich beschäftigt, versuche das aber demnächst einzubauen.

**Comment by Woersty** [comment]
Ab Version 1.1
