### ISSUE TITLE
Mail

### ISSUE THREAD

**Issue by Cobru** [Woersty/LoxBerry-Plugin-cam-connect#10]
Sicher würde es Sinn machen für Unterschiedliche Cams Unterschiedliche Maileinstellungen zu hinterlegen

**Comment by Woersty** [comment]
Dafür gibt es die Option
`&email_to=mail(at)woerstenfeld.de`
![ermitteln](https://cloud.githubusercontent.com/assets/20454116/20167767/fcd1e9ae-a71d-11e6-8e07-aacece81480a.png)

Warum reicht das nicht?

Edit: Drüber nachgedacht.... Also der Name der Cam als Absender. Alles klar. Kommt in späterer Version...

**Comment by Cobru** [comment]
genau

**Comment by Woersty** [comment]
Ist aufwändig. Keine Zeit. Später.... 😢

**Comment by Cobru** [comment]
OK Schade ist mir nur gerade mal wieder so eingekommen

**Comment by Woersty** [comment]
Bin dran...

**Comment by Woersty** [comment]
Eingebaut.
