### ISSUE TITLE
Axis Cam

### ISSUE THREAD

**Issue by Cobru** [Woersty/LoxBerry-Plugin-cam-connect#11]
Hallo Wörsty die Axis Cam kann zwar Bilder Speichern aber der Mailversand geht nicht über den MS .
Könnte man die Cam auch hinterlegen
http://x.x.x.x/jpg/image.jpg

Eventuell könnte man ja manuell Cams hinzufügen ?

**Comment by Woersty** [comment]
Ja.

**Comment by Woersty** [comment]
Ab v1.9 gelöst.
