### ISSUE TITLE
Virtuelle Ein- und Ausgänge

### ISSUE THREAD

**Issue by wick0310** [Woersty/LoxBerry-Plugin-cam-connect#17]
Hallo
Eine Frage ist es auch irgendwie möglich eine mail mit Foto über einen Virtuelle Ausgang zu versenden also so ähnlich wie bei dem Baustein Türsteuerung? Denn ich möcht gerne eine zweite Kamera (Hinter dem Haus) eine Benachrichtigung haben. Die Auslösung würde ich über einen Bewegungsmelder machen. Einen Teil habe ich schon gemacht  was aber nicht funktioniert ist das Foto was ich bekomme ist nicht das aktuelle, sondern ein altes. Da du dich mit dem Thema sehr gut auskennst frage ich dich mal direkt ob du da eine Idee dazu hast
 mfg Wick

**Comment by Woersty** [comment]
Du kannst doch einfach die LoxBerry-Adresse in den Virtuellen Ausgang schreiben und in den Befehl dann den Rest und ihn dann triggern oder nicht? Im Script ist ein [sleep 0.4](https://github.com/Woersty/LoxBerry-Plugin-cam-connect/blob/master/webfrontend/html/index.php#L144) drin. Das legt fest, wie lange er vor dem Bild wartet.
`http://loxberry in den Ausgang`
 und 
`/plugins/cam-connect/?kamera=Kamera-Hostname&port=80&user=Benutzername&pass=Passwort&cam-model=1&email_to=name(at)domain`
 in den Befehl.

Und das geht nicht?

PS: Ich habe Caching Probleme bemerkt da bin ich noch dran. Ist das Bild auf dem PC oder iPhone "alt"?
Ist es das gleiche Bild beim Weiterleiten der eMail?

**Comment by Woersty** [comment]
Probier mal die 1.9.7

**Comment by wick0310** [comment]
Hallo
Habe mal die 1.9.7 installiert und wenn ich das gleiche Bild bekommen dann ist es immer gleich PC und iPhone dasselbe. Und ich werde das nochmal versuchen Virtuelle Ausgaben

**Comment by wick0310** [comment]
Hallo 
du ich wollte dich nochmal fragen ob das Problem mit dem gleichen Bild mit der zu kurzen zeit von  sleep 0.4 zu tun haben kann ? gibt es eine Möglichkeit die zeit zu verlängern ?

**Comment by wick0310** [comment]
was ich jetzt bemerkt habe ist das das Bild schon richtig ist aber am Handy falsch angezeigt wird das heißt die Mail am Handy ( Iphone ) ist nicht richtig im Mail account  ist sie schon richtig kennst du das Problem ?

**Comment by Woersty** [comment]
Kenne das Problem. 
https://github.com/Woersty/LoxBerry-Plugin-cam-connect/issues/15
Dachte das geht inzwischen?
Hast du das Problem mit der aktuellen Version 1.9.7 noch, ja?

Mist 👎 

Am sleep liegt es nicht.

**Comment by wick0310** [comment]
Soory 
das ich mich erst jetzt melde ja habe ich leider noch kann ich da was machen ? oder an was liegt das hat das mit dem Iphone zu tun ?

**Comment by Woersty** [comment]
Hatte noch keine Zeit und Lust mich weiter damit zu befassen. Aber bei mir geht es aktuell auch nicht...

**Comment by Woersty** [comment]
Wenn ich auf weiterleiten tippe, sehe ich aber das korrekte Bild. Also wird es am iPhone liegen...
Ich suche später nach einer Lösung.

**Comment by Woersty** [comment]
Caching geändert. Müsste jetzt passen.

**Comment by Woersty** [comment]
Achtung! Die aktuelle Version hier im GitHub ist nicht mehr LoxBerry 0.2.3 kompatibel.
Letzte Version war die 1.9.8
[LoxBerry-Plugin-cam-connect-master_v1.9.8.zip](https://github.com/Woersty/LoxBerry-Plugin-cam-connect/files/1691221/LoxBerry-Plugin-cam-connect-master_v1.9.8.zip)
