### ISSUE TITLE
Cam Plugin TV-IP302PI

### ISSUE THREAD

**Issue by wick0310** [Woersty/LoxBerry-Plugin-cam-connect#3]

**Comment by wick0310** [comment]
Hallo finde richtig gut was du/ihr ihr alles macht 

Jetzt meine Frage kannst du das plugin auch für eine Trendnet TV-IP302PI machen oder diese -kamera einfügen ?

**Comment by Woersty** [comment]
Wie ist denn der URL für diese Kamera?
Eigentlich muss das dann nur in die camera_models.dat unter /config hinzugefügt werden:
`Trendnet|TV-IP310PI|/Streaming/channels/1/picture
`

**Comment by Woersty** [comment]
Kannst du mal http://xx.xx.xx.xx/GetImage.cgi aufrufen?
Was kommt da? (xx durch deine IP ersetzten )
Laut dieser Seite http://www.lavrsen.dk/foswiki/bin/view/Motion/TrendNet könnte das gehen.

**Comment by wick0310** [comment]
Hallo und danke für deine Antwort und ja mit der URL bekommen ich ein Bild von der Kamera. Danke für deine Hilfe und eine Frage habe ich noch das mit dem Bild versenden per Mail kommt schon noch hoffe ich zumindest?

**Comment by Woersty** [comment]
Ok, bin dran. Die nächste Version sollte dann deine Kamera können.

**Comment by Woersty** [comment]
Gelöst mit https://github.com/Woersty/LoxBerry-Plugin-cam-connect/commit/ba9eeeec783b0b5d7d86e9958654c039eca94a30
