### ISSUE TITLE
Czech language translation 

### ISSUE THREAD

**Issue by KaZaNvanHyena** [Woersty/LoxBerry-Plugin-cam-connect#31]
Hi, we finished Czech translation for current Cam-Connect plugin. 
Please add it into next release if possible.

https://github.com/zmata/LoxBerryCz/tree/master/plugins/cam-connect

Thank you
Pavel KaZaN Sytař

**Comment by Woersty** [comment]
Thank you too. 👍 
https://github.com/Woersty/LoxBerry-Plugin-cam-connect/releases/tag/v2018.4.3
You can use the Plugin update function.
