### ISSUE TITLE
Cam-Connect müllt Postfach zu

### ISSUE THREAD

**Issue by mschlenstedt** [Woersty/LoxBerry-Plugin-cam-connect#33]
Wenn die Config-Datei fehlt, müllt Cam-Connect das Postfach zu - ca. sekündlich eine Mail. Nach 200 Mails hat mein Provider meinen Mailaccount wegen Spamverdacht gesperrt :-(

![image](https://user-images.githubusercontent.com/16830799/42897845-9441b106-8ac1-11e8-9fd7-066591e1a94c.png)

**Comment by Woersty** [comment]
Upps. Schau ich mir übernächste Woche an.

**Comment by mschlenstedt** [comment]
Generell sendet das Plugin extrem viele Benachrichtigungen. Ich hatte 175 Notfications in der GUI - da war Christians "Alle Nachrichten löschen"-Button Gold wert :-)

![image](https://user-images.githubusercontent.com/16830799/42983901-b000e1ae-8be9-11e8-8c18-110bcd3df8b1.png)

**Comment by Woersty** [comment]
Wenn dir das zuviel ist, dann setz halt das Loglevel runter. 
Ich habe das mit der Konfig-Datei auf Warning gesetzt.
Das mit dem Error E10 kommt ab Level Info. Soll auch so.

**Comment by Woersty** [comment]
Gebe keine extra Version heraus. Kommt dann mit einem zukünftigen Update.
