### ISSUE TITLE
Kleine Anpassung der URL

### ISSUE THREAD

**Issue by Kropiunik123** [Woersty/LoxBerry-Plugin-cam-connect#34]
Hallo 

Wäre es möglich vielleicht möglich selbst zu definieren welche URL aufgerufen wird.
Mir fehlt im Befehl einer konfigurierten Kamera eine Kleinigkeit. 

So funktionert es nicht:
http://192.168.1.250:8888/cgi-bin/snapshot.cgi?channel=1

So funktionert es:
http://192.168.1.250:8888/cgi-bin/snapshot.cgi?channel=channel1

Danke

**Comment by Woersty** [comment]
Bitte einfach wie in der Hilfe beschrieben ein neues Modell beantragen und URL? Hersteller und Modell angeben.

**Comment by Woersty** [comment]
Siehe #35
