### ISSUE TITLE
Cameralist update request

### ISSUE THREAD

**Issue by Kropiunik123** [Woersty/LoxBerry-Plugin-cam-connect#35]
Please add the following camera:

Videra Recorder
URL ist identisch wie Luna nur kommt am ende nochmal der Kanal.
http://192.168.1.250:8888/cgi-bin/snapshot.cgi?channel=channel1

**Comment by Woersty** [comment]
Geht es, wenn du diese Version nimmst?
https://github.com/Woersty/LoxBerry-Plugin-cam-connect/archive/master.zip

**Comment by Kropiunik123** [comment]
Funktioniert leider nicht.

Cam #1: E04: Kameralisten-Lesefehler

**Comment by Woersty** [comment]
Ich Trottel. Hatte CURLAUTH_DIGEST vergessen. Bitte nochmal testen. Gleicher Link.

**Comment by Kropiunik123** [comment]
URL wird richtig aufgerufen, jedoch bekomme ich jetzt die Meldung E10 Bild zu klein.
Wenn ich die URL im Browser eingebe wird das Bild sofort angezeigt

**Comment by Woersty** [comment]
Vermutlich bekommst du kein Bild sondern eine Webseite zurück. Bitte mal Loglevel auf Debug stellen (Plugin-Verwaltung) und nochmal testen. Im Log siehst du dann was kommt.

`[01-Aug-2018 00:04:26 Europe/Berlin] Wednesday PHP: Cam #1: Call get_image() fist time
[01-Aug-2018 00:04:26 Europe/Berlin] Wednesday PHP: Cam #1: Function get_image called (0) for camera 1 with hostname/IP: kamera-vorgarten
[01-Aug-2018 00:04:26 Europe/Berlin] Wednesday PHP: Cam #1: Check for 'Digitus DN-16049' camera model
[01-Aug-2018 00:04:26 Europe/Berlin] Wednesday PHP: Cam #1: It's no 'Digitus DN-16049' but a TV-IP310PI camera - continue normally
[01-Aug-2018 00:04:26 Europe/Berlin] Wednesday PHP: Cam #1: Get the image from the camera: http://kamera-vorgarten:80/Streaming/channels/1/picture
[01-Aug-2018 00:04:27 Europe/Berlin] Wednesday PHP: Cam #1: Image successfully read from the camera.
[01-Aug-2018 00:04:27 Europe/Berlin] Wednesday PHP: Cam #1: Type: image/jpeg Size: 45316 Bytes`

Muss gleich mal fist gegen first tauschen....

**Comment by Kropiunik123** [comment]
Die LOG-Datei ist leer, gibt es noch eine Lösung?

**Comment by Woersty** [comment]
Das kann nicht sein. Bitte nochmal testen. Im log muss was stehen. Und natürlich das Plugin aufrufen wenn auf debug umgestellt ist

**Comment by Kropiunik123** [comment]
Es steht wirklich nichts in der Datei

![screen](https://user-images.githubusercontent.com/41581253/43816891-2cdb6d4c-9ad7-11e8-85c0-06dbfd8af5bd.jpg)

**Comment by Woersty** [comment]
Das ist schlecht. Dann ist vermutlich dein Dateisystem vom Loxberry voll oder so.
Kannst du mal auf der Shell df -h eingeben? Mal einen Reboot versucht?
Die Logs sind im tmp Verzeichnispfad und werden beim reboot gelöscht.
Ist die Datei vorhanden, wenn du über die Samba Freigabe in \\192.168.1.76\log\plugins\cam-connect\ schaust?

**Comment by Kropiunik123** [comment]
![screen1](https://user-images.githubusercontent.com/41581253/43836598-1f21633e-9b16-11e8-9fb5-6cdbf7924b48.jpg)

**Comment by Woersty** [comment]
Mist. Scheinbar ein Redirect. Kann ich mal eben mit Teamviewer gucken? 
Mail mich mal an mail(ät)woerstenfeld.de dann schick ich dir die Handynummer für WhatsApp oder so

Viele Grüße
