### ISSUE TITLE
Cameralist update request

### ISSUE THREAD

**Issue by marcelzoller** [Woersty/LoxBerry-Plugin-cam-connect#36]
Please add the following camera:
19|Axis|M3114|/jpg/image.jpg|CURLAUTH_DIGEST
20|Axis|M3017 View 1|/axis-cgi/jpg/image.cgi?camera=1|CURLAUTH_DIGEST
21|Axis|M3017 View 2|/axis-cgi/jpg/image.cgi?camera=2|CURLAUTH_DIGEST
22|Axis|M3017 View 3|/axis-cgi/jpg/image.cgi?camera=3|CURLAUTH_DIGEST
23|Axis|M3017 View 4|/axis-cgi/jpg/image.cgi?camera=4|CURLAUTH_DIGEST
24|Axis|M3017 View 5|/axis-cgi/jpg/image.cgi?camera=5|CURLAUTH_DIGEST
25|Axis|M3017 View 6|/axis-cgi/jpg/image.cgi?camera=6|CURLAUTH_DIGEST
26|Axis|M3017 View 7|/axis-cgi/jpg/image.cgi?camera=7|CURLAUTH_DIGEST
27|Axis|M3017 View 8|/axis-cgi/jpg/image.cgi?camera=8|CURLAUTH_DIGEST
28|Axis|M3017 View 9|/axis-cgi/jpg/image.cgi?camera=9|CURLAUTH_DIGEST
29|Axis|M3017 View 10|/axis-cgi/jpg/image.cgi?camera=10|CURLAUTH_DIGEST
30|Axis|M3017 View 11|/axis-cgi/jpg/image.cgi?camera=11|CURLAUTH_DIGEST

Super cooles plugin. habe noch meinen zwei Typen von Axis Kamera hinzugefügt.

**Comment by Woersty** [comment]
https://github.com/Woersty/LoxBerry-Plugin-cam-connect/commit/bd2a082b5e7772b12f9c62c6949ddcf156ef1f05
