### ISSUE TITLE
email error E22

### ISSUE THREAD

**Issue by tom3737** [Woersty/LoxBerry-Plugin-cam-connect#37]
Mailserver on Loxberry is configured and test-email is sent successfully when mailserver configuration is completed. But Cam-Connect gets an error message (LoxBerry version v1.2.4.6, Cam-Connect version:  v2018.4.3). I have another Cam-Connect installation (LoxBerry 0.2.4, Cam-Connect 1.9.8) with the exact same configuration which works perfectly fine!

Here the error message:

Cam-Connect Plugin benachrichtigt über die folgende INFORMATION:
__________________________________________________

Cam #1: E22: Fehler beim Versenden der eMailCode: 1

**Comment by tom3737** [comment]
Additional remark: I've changed LogLevel to Debug, here is the log file (I've replaced the email adress by "XXXXXX"):

[28-Oct-2018 07:01:59 Europe/Berlin] Sunday PHP: Cam #1: eMail-Body will be:
[28-Oct-2018 07:01:59 Europe/Berlin] Sunday PHP: From: LoxBerry 
To: XXXXXXX
Subject: [Eingang] Es war am 28.10.2018 um 07:01:57 jemand an der Tür! 
MIME-Version: 1.0
Content-Type: multipart/alternative;
boundary="------------6fa27353a43fcf9a15d9b6c0e9947484"

This is a multi-part message in MIME format.
--------------6fa27353a43fcf9a15d9b6c0e9947484
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 8bit

Hier das Bild: 

--
Viele GrüßeDein LoxBerry

--------------6fa27353a43fcf9a15d9b6c0e9947484
Content-Type: multipart/related;
boundary="------------7bf1ab26df955b0a6acae154433bedb4"


--------------7bf1ab26df955b0a6acae154433bedb4
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 8bit







Hier das Bild: 


Snapshot_2018-10-28_01h07m07s_1.jpg


--

Viele Grüße
Dein LoxBerry 

--------------7bf1ab26df955b0a6acae154433bedb4
Content-Type: image/jpeg; name="Snapshot_2018-10-28_01h07m07s_1.jpg"
Content-Transfer-Encoding: base64
Content-ID: 
Content-Disposition: inline; filename="Snapshot_2018-10-28_01h07m07s_1.jpg"

NIzSEU6kPSgBuPeiiigBMUg4606j8KADGaKUHmkPWgApV60lKvWgBR1paOlL1FACUUZFFACjig9KbS5oAqXUeHEvrx+NMW7m3Lg5IHerjJvRl9uPrVEDKkbcNQBJcXBuSGZAGA7U0zuYxGQCnoRSxqwuBhhkcjjr7U1VbkL9wc0ANDksjMCYweV9R3qzd/ZGc/ZkZexAGBUMUjRN6HB61GQwKnrmgCZ4CQOdoABBNWoRvRt3Oeh75qmlxJnqSAOQelWo7pTGd2Fb2FAHoBZfUU3cn94ZquQKQ9KALO9P7wqPzFz1FQUh9s0AWlkQEHcKrzuGmYjoTTO9BAzQBH3pO9OpCKAG02n00j0oAaaaelOPpSUAIRxTDUlNxk0ANpMU4jB60lAC9YyPQ0zNPXowNM47UAKOtSAg1HzkVIAKAEI5JoBxS0gHrQAhHeilOaSgBCKSnU2gBD0ptOpCPQUAN7UUuKSgBDSEZFKaKAGdDTs4oIptABSHpS/hSGgBKQjNLTQTnmgBOlFB9aSgAIpKWkPtQA1utNbrSnPekNADCe1JQetFACNwKO1BGaQk+lABSfyopaAEo9aWkPSgBtFFFACZpG6UtBoAM03Ap3FIaAEIzSAgGnUmBQAmRSA4pSOeBSUAAPNPHNR0o4OaAHZFNp2OcGkIAFACDrT6Zg04Z70AKcUUmKWgApPSjFLmgAHWomTbMWxkGpuMVFOCYWweetAFa4Yh+Bg98URllQkc7uKlktlS4w8jBXQOpC5yDV+0tYPs0k6lpI0ILAjGKAMmSJiSd3HUZoiGSQeM9DWhFEs7P8px254FVXsmSQIJlaYn5Y1/qaAIShTIUgnpxS+UQMA/MOSSackLrcESAZ74NOlhYEhWBXqCD2oA70009KcRk000ANpCcUpz3ooAb1oIwaCKTJPWgAIzTaVvpSUAIRwTSUtNNACMO9NxmlPWkJx0oAQiikoLUANbrSE0pOTSZoAcvJpnegHBzQT3PegAX1qQdBUXPanjmgB/eim7X9OKd5bdyKAEbpTKf5TY5PFNxg0AFJS0hoAQ0UUUANPSkpW6UlACGkoNFACHpTadQRnvQA2mnrTqaRQAUhGaWigBpOOKSnHkU2gBuaKU9KbQAhpjHAp7dagbdyaAFJ70gOaQA4FKOKAAnFHajOaTvQAlFLRQAU0mnUlACEYpKUnNJQAUhGaM0tADaT+VKRRQAUUUUAIaaTmn01qADHGaTPGKcOlFACbjQTmkAGSOxpehNAADilBzSZzxSd6AF3UoOabjgUueMUAOpg60oOKQHmgB9KKQHIooAfJP5dpb5UExsVyRxtPOKnZlSyMSttSb5gAf0qlIu9PpzURZigDMOOgoAsRzG2JXb8rHpnmq6Mk96GbILPgnPIpolUtmVfYUbDFJ56rwvPJoAbdqLe4wnT1JqQHZAko5DfeqrMS7785Dc4qVJAYlU5HY0AegnikI4p5HOKaetADCKbUhGaQigBhHFNxUh+7TaAGYz1pp608gikxQA2m04jFNPAoAacfjTetP200jBoAbTMGn0UAMNIBTyM0ygBKQ5zS0UAFPj6/hxUdSJwaAJQOOetKRyTnHNLglc+1IehGaAE9scA1E33uamIPI981DJwxoAOKSgDilIxQA0ikp1IaAGt0puKU9KTPGKAExQRS0hoASkOO9LSEZoAaRRQTmkoAQ0UHrSUAB6UynnpTKADrSU6mnrQA1utNNObrTTQBGetFB60UAJig0tIRQA2lpKWgAoopKAEIpKCc0p+7QA2lpQCRmkoASgig+tJmgAopKWgApv1p1FABSUtJ2oABjPFJwWNKBikAwD69qAAjB4pKd1+h6Um0noMmgBKSn+W2BkY+tKFVfvOPwoAZj2owak3xgkYLfpR5pHQAfhQA1VY9AcfSnbSOSRims7Mck03JxQA/CgYycGqTbwSnHWrROar3Axhj06cUAEsDLFyePT1qJJzGpVhke9AZtuCflFK8LO+cgqf4u1AEYAkbEYJPpSRKzylTuUmpF22028HJFKHM0wkkGAfSgD0fqKTFPIpuOaAG54z6GmEZNSEU0jpgUAMxxTSoJp5x0pDQA0jFNPSnGkoAjIzzSU8imkUAMNNbrT8UhAzQAyk96ceKaeBigBM5phGKd0o70AM7UEU7HPNNoASnLwQaTilGPwoAsAcj60HHGfSkDHFOPb60AJjAJ9qikHy59al56U1wNtAES/dpW6Ui9KUjNADaQ0p60h96AGk4pM0tGB6UANppNOPWm0AFFFIc9qAG0lL3pO3NABmkJoNFACdqaTmnE8U2gApp60uaQmgBrdaaacaZzQAw9aKUjmkoAKb3p2ab3oAXrSUuRSUAIO9LRTTnPFABtpO+KUHHWk70AB4NFFFABRRRQAhpPpSmkoAPrRRRmgApM4NLSHGeaAF70gyrBvSkJ9KTJoAfuCnG0exoEjnIBwKaTkDI5FJ3oAUZzzSHrTuKaetABR6UY7iigAopM9qWgApkih4ytOo7UAU9qhMAg+uaBvIKjAWluFw+exqIsQmFHPegCZWtxCyyRsXPSq3IwDViKOWSMCCNnJ64GcUhVo2YSAiUHkHtQB6ZTSO9PPXFJQAymkU8jNMxzQA09elNIzUmKaRmgCPGTTafij2oAjIzSMKeetNbpQBH3pMU8800jFAEbdqbT6aetADT1op1NIxQAh6U2nEZFJtNADcZpR6UlLQBOrfLjHandajj+5Tu9AATg/jSHlTSjpn1pQcAj1FAEC9cUp4pp+9inHpQA08nNJilpM0AJSHpS0h6UANJzTaWkIoASk3Up6U0DIPbFACE0maU9KSgAoopv3qAEPWkJxS9KaaACkpaTOKAGkYpDSk5pnPegBCe1JS4JNJQAhGaSnUECgBmQBSkUox2o4FADaOe1OJwMgD8KbkmgAIJpCMCnUh6UANopQeKSgBKWiigBAaQ9aKKACkxgHHWlpCcUAHamnrTs8Zpp5NABRRQBk0AKB60EYo6DFJj8vWgBcCkPBopO1ACg4opAMUHpQAlKDTetHPagB3WikFHegBkybkIAOetVY3aIiRfvA9CM1ezjtWfMhjYlScE0AX7XUp0lITYqsOVI4qndTSXF1JIw574quQSeeTViN3iIbHzDrQB6gV5PHekx7VKw5NNI7UAREUzFSkYptAEZ6UlOPWmmgBhBBppFSEZpp9KAGU2nmmUANPWmNUhFMI4zQA00wgU800jNADcUmM07OMikoAaeKQ9KcRTaAGUDrSkYooAkiPJp44f8aijOGxUpxn9aAG+/TFLnpQQOopKAIXyGpwPPPSlkByT6UgXKg0AIetIRTtpzSEYNADaQ9KU8d6O2c0AMwaafU/lUmRTCRQA3Ipp6U8kZpC3pQAykIpSaTNACHPakPHSlJxTKAFpOKD0pKAA4ppPFKeOabQAZ56U0tSk1GTmgBSxz1pM570h6UgFACmkxS9aM9qAE6UvWkPWl6UALTT1FGaCaACkxSBs0tABgelIeelLTQcUAFJmlpp60AFFFFABTfrTqQjNACEjFNz7UtFABQPaigcUAB4Oe9BOVx0oJzRQAnSgnig0nbFABziiiigBD0pOT3oPWkBwKAHZ9OaCRupucUZzzQA7IqC4G5M4qWkYZUigCpEzK2VXJpwSZyZGAIHJp6CRJRsAweM0PI4hdHGCT2oA9UZeaYeKlYYNRt1oAYRkg0wipDTMUAMPIppGKeRSYoAjximk54qQimEdcUAMI5pKcfekI5oAjNNIqQimkUAREYppHepDk03FADMCmkYp54NIRQAykNOIpPyoAjIxRTsc8000AA+9mpewqKpe3FAC5AwKaW5pTggc0hHze1ADXORTEansPk9OKiU8Y70AOLHNIaKToaAFppPBoJ44pKACm0ppp6UAIT2pKKQ0AITSE4NFNPWgBSc03pSHk0GgAopCabmgBd3NIaKQmgBKYRg5p9NY5PFACU09aU9KSgAooooAKKTNLQAUUU09aAFJxTe9FFABRRRQAUh6UtIetACUUGigBD0pGz2p1NagBuTS0UUAFJk0tFAAeKaaU0lACD6UHpS54NN6DGaAE5ooooAKQnijNHFACDrSkc5pKXPFAADR1oBoHWgCvcbkwyk9ah8w8knINXJBuQis4naaAPY3GDTCO9TMvJphGM0AREE03BPWpSM02gCMqMU3FS4ppHNAERGabU20Uxh1oAhYA00qO1TbeOaZjnNAEZFNIqQimkZoAi200qM1KRk0hHFAEJFIRmpSOaay0AREc4pNoqQj3pMe9AERppUZqeRVGNhzURoAjIwakXlcUhp0fSgBdpAzTSSKd0UdaQ88e1ADG5UioRw1TnrUL8NQAtNYjvTs96YTk0AFITQaSgAzTCc04nFNPWgBDSE8ZoI5zR0FADCc0lLSHpQA2k3GlJxTaACjIPSjpTTzQAZo70UhOeKAEzzSUEYpM0AB6UlLmmkZoAKCabRQAvUZpMmik7UAOB5oPWkpR0oASiiigAooooAKTFHTmjrzQA3vS0DiigAphOacT2ptABSZ5paQigBaKbRQAp6UlH1ooAKaetKTgUmeMUANJwKAc0E4pM80AHeg0NzzTd3tQAp4pATmnDkUnNAC0U1qCc0AOqCS2DvuDY9RUlOY4QkdcUAesyoUY1EV71oXMeVLVSI9RQBCaTHtU2M0wrQBERQQM1JikYDNAEZHpTCp9KlIwKQ0AQkc0xhipiMj3pmOaAISKTHtUpXmmkc0ARFfamkVNimlRQBCRzTSDUxAppAoAippHPFSH0pp4oAjIph5PFSkU0igCIjmlTg0p60L96gBevTsab2Gexp3fPrTSDmgBpPNRSCpSOtRyDigBoxikalXpSNQA04xzSUtIetADTTTTm602gBKKKQmgBtNNKaSgBKbTicU2gBCaSg9aKAEPSkzx70detIetABTcYp1IaAEpO1LSHkUANooooAKKKKACj2oooAKKQ0UALRRSGgBDmijNFABSE54FLSYGaAGnrQRilPWkJzQAUnalpKAEooAooATIFIT6UHk0EYoATBPJooJzRQAmKafWn0wjNAB1FIMDrS98Uh5NAC5FBpCMUmTjFAB70UUUAKMYpcr3ptFAHtcqFlIqiV4xWq465rPlXDEUAVyMU08VKRz0pCvHSgCLHGKTbUmO9JigCIjNIRxUhWmleKAIiMGm4xUmDTSPWgCMimbRUpFNI9qAIttNI7VKRTCDmgBmKYR71L0ppFAERHFMIFSmmkUAREEVGRk1Nio2+lADCO1Nx8wpxphzQBIemKae1O5K0jfSgCMjPSmOPlIpxz+tIehB60AQLw2KVqD9+hu1ADelIeaU9KSgBhGKQ05qaaAG0n3acaYTmgBD0pKU9KbQAjdaSlammgBD1pCcUtJQA2kzzS0hoAD1pCMUooJoASiiigBpOaTvRS8YoASiiigBDRilooAKKKQ9KADNB4pD1o570AL1pOlL2pKACmHrT6Q9KAG0UUUAFNPWiigApCcUp9qQ+9ADTyaKD1pKAFpM80UmeaAHAFjtHWm0oyGB9KGGD9aAEooooAOKBSYox70ALSEZpcUUANxim0800jigD3R+TVS4jzyO1XSMGopVBBoAz8Cm4qQrgkelNIzQBHjtTCpzxUxGKaRQBERQRxTyM00+lAERHNNIqUimEYoAjK8UxhgcVLznpTSKAIiPyppFSYppHNAEZAphFSkZ+lMbtQBER3FNIqU9KYwzQBEaYQMVKRgGmUARMBmmEZFSFaYRigAXlTQehNCY59aCeooAj/wzSdGNOx0/Km4xQBC3380jUsg5poGaAEPSmnpTjSGgBhOaQ9Kc3WmnpQA2kIxTj2pCcUAMNJSmkoAa1NNObtTTQA09KTJp1IRk0ANooooATp0pKdTSMUAFFFFADQM0uBS00ntQAYFAoB4xQRigBDRS54xSUAFJS0UANPWgmlIpKAExQc0tFADMmgkmgjFFABRRRQA2inUmKAEpD0pSMUUAMooPWjvQAlGKWigApWHFJQBmgBveilI+aloAbRRSjpQAnSilIo60AJTW606kJxQB7s4wcCmEcGpG61G3egCjMu1/Y1GatypuGfSqhoAbSN1pTTc5oAQ9KaRTjTaAGkUwjIp+c02gCM9KbTm702gBuCKYeDTzmmEZNADTimds088UygBhPtTGp5700jvQAw9ajINSGmnpQBEaYakbvUZOKAGL9807IyaaeDTsDNADW4P60w+1PPamFucUARyCo6mcZFQd6AA9Kb0px6U3rQAjU0049aZk0AJ3xSNTqa1ADT0pp6U49KSgBh96Q05qbQAlFBooAZRRRQAlJg06igBvSkpaKACmEU+kPSgBB0owaVelLQAyilI4zSUAIaKWigAptOpKAEooooAQjNNINPpG6UANpO9LRQAmRSGg9aKADtRRRQAhFNxin0mMmgBuDTh0obpQOlACEelIOpp9JjBoAGGACO9Np/VSPfNJtFADKWlIwOKSgAxnvRRg0UANIop1NNAHuzHFRt0p7HI96izzigBrdCKosME54q6WGaqXA+YHtQBETSUhNNJxQApINNJ7UFsdKZyaAFppOKCSOKYSe1AATTfWkJ/Okz15oACc0w8UE800mgAPrTCcUpbmmHmgAbHamE0pOKYTQAhqPvT2IphoAaajPWn9BzTDQAwnJp2M80w8Zpwb5cd6AExyeaacYpzdaYeQaAGk8NVfODip+9QSfeoAU0lKelJQA3b700jNObrSZxQA2mnrTqa1ADT0ptOPSoz1oACc0gFLSE0AIetFFFADW6UlFFACE4pCc06mmgAo6UUUAFFFFABRRSGgBM54pCMU4UhGTQAlFLg0mDQAUh6UtFADaKU03HvQAtNI706kI4oAbRS4pDg0AIeaMUtFADTxSDOemBT6KAG0UtLQAmKTAp1NPWgAopdpPagrQAnehgVYjrT/AJQOBzSOSy7vSgBtMPWn0hFACA4pCMU4D1pMGgBKQincAYpKAPcjioWPJNPbpUbe/egBhPNQzDctStTGGBQBS/Gmt1pZBtb2plABmmknmlJxTetAAajPHSnGmtQA0mmnnmlIppOKAEJ45pCcilpjd6AA4NMNFJQAhPFMPSnEd6YetACEZpppxOBTD0oAYx7dqaac3WmmgCJqF5zSkZpoOGxQA7JxzTKeTk009f1oAZ7+9RSjvUp6mo5BlaAIwfloPSkU9qU9KAGk5pKWkPSgBDTWpT0ptACHpTD1pxNNJ7UAJTadTSMUAFNJwadSEZoAbRRRQAU2nUd6AG0UuKMUAJRQRijHGaACiiigAooooAKac06igBuOKSn03b70AJ1pMUtFACYFBFLRQA2k207FIRQA0DmkI5p9GDQAylIGKdgGnbVAzQBEAT2p22n/AEpDQAzbjrS8en40tFABTTmnUUAM70pHOKXHOaWgCKinFQGyKQ9KAEooIxSgUANIptPPekHFAHtZNMc07NMbrQA2oyacx44phPzUAV514zVYkEVdcZ4qkwwxFACe1NNKfWkoAQmm0pxj3ppOKAENNPWlpDjuaAGmmnkU400nAoAaRim0pOaSgBhpCKU9aTNADDTTT8ZOaYaAGEU09aeelMNAEZ6009ad3ppoAdTOvSn/AEpOmcUAR96Y3K49Ke3FNIFAFfODzTjyKRwAaTJxQAU2nU3OaAEPSm0pPOKSgBD0pp6Uuaac0AJSGlo60ANpCDmlNFADCMUU4jNNPWgAooooAKKKKAE6daD0paKAGg0pFIaMmgAopcUYFACdaMUuKXrQAzGTS4NLiloAZijinYo20AMNJUmKMUAR4NG01IQKbQA3GKKd1owMUANoxSgetLjNADaQinYwKSgBMUmMU6kPSgBKKUCgigBKKKKAEIzTafnmmY5oAKQClwaKAEPFN7mne1JigD2o1G3BpWJxzSEcUARNxTSMCntUZOKAG96rTphtwqyeaZIu4YoApHpSUrcHFNPSgBD1pppaQ0ANPSm8U6mmgBDTT0pTxSHpQAzHOaSlptADG70lO65ppGaAEJxTTzQRQelADTUZFP7Gm0AMbpTCKe3SmZoARelKf50i9aXrmgCNl4/CmnoD2qU8D6Uw46DpQBXkHNNqWQfKahFAATikp1N7n2oAaetJQetJQAlJjPFLSHpQA09aQnFLRQA33opT0pKACmkd6U0g60AJRSnrSYxQAUUYo5oAKKMGlwaAEpAMU7bRgLQA00AGn8YoFACbaMAdadRQAcdhSE4paKAG5zxSEYp9JQA2ilwaSgBMUhAzTqKAG0UuKMcUAJS4oApaAExSECnUUAMIzSEGnYoxQAyk60+gjIoAZ0FHWlooATApDxS0dqAEplPphGKACiiigD2Qn1ppPelPWmnpQAzPrTGp5GRTGoASmmnUhFAFSZSGzUOKuTLuWqmMcUAMPBpDTj1HpSUAMPvTTTm64ppGKAGnmkJ4pSMUh6UAMpKWkoAYaaetPI700jmgBuM0w1JTDQAw9KbjFPPWmtQBG3SmEcZp7dKYelACDhvrSnpim96d1BoAbwfpTc9Kd0BpnRfxoAYxyDgVCetTnnNQuMMaAEppFOpD0oAbim9qdSEE9jQA0im1JtNNKnPagBuBTakx6mmkr3yfrQA00mBTty+lBfHQCgBmD6UBDnNKXJ6mgZx1oANvvQQKWkNABxSUUUAFFFFABSEZpaKAExR0paKACilAxSHrQAlLRxRQAUUUUAFNIp1FADQOKAPWnUnc0AN70UvTmjGeaAEopwGKbQAUUUflQAUhxS009aACignNITigBDikoNFABSe1B4pO9ACNkHik69acabtoAQ9aKD1ooA9jyKYzflTqjbofrQAmc00nNBptABmkJoPWkoACMiqkq7X+tXKrXH3hQBB2ptO7U2gBvem45p38RpDQBGevtSH0pzfdNN9PpQA0jHFN6U5utIaAGnpTacelN7UAMx75pCc06md6AGnrTMY6089aae1AEeeaa3epDUbUANpQRikpB0/GgAPIphPNSDrTH6rQA3JyDUL/AK1KOg+tNfpQBGpUDJGTRkdhTew+tFADi3HSmFjSmm0AITmmd6d60w9KACkJzTuwplACHpSAUp6UCgBKKSigBaQnFFIegoAWlpB0ooAWikooAWikooAcBS0g6UtACHNJ0p1NPWgAo60lOFADT1paSigBaSijsKAFopKKAE6HJo680N0pR0oAQnNBIxSdzRQAUUUUAJmjNNooAWmZ5p1NPQ0AB60maWmP1FADiaSil7UAJikIzThSUAJjim049KbQB//Z
--------------7bf1ab26df955b0a6acae154433bedb4--

--------------6fa27353a43fcf9a15d9b6c0e9947484--


[28-Oct-2018 07:01:59 Europe/Berlin] Sunday PHP: Cam #1: Write eMail tempfile /tmp/cam_connect_pm7zKu
[28-Oct-2018 07:01:59 Europe/Berlin] Sunday PHP: Cam #1: Sendng eMail from tempfile /tmp/cam_connect_pm7zKu
[28-Oct-2018 07:02:00 Europe/Berlin] Sunday PHP: Cam #1: Delete tempfile /tmp/cam_connect_pm7zKu
[28-Oct-2018 07:02:00 Europe/Berlin] Sunday PHP: Cam #1: Sendmail Ausgabe: sendmail: 501 Syntax error - line too long
[28-Oct-2018 07:02:00 Europe/Berlin] Sunday ERROR: PHP: Cam #1: E22: Fehler beim Versenden der eMailCode: 1

**Comment by Woersty** [comment]
Seems related to the Mailserver. I guess there is a CPL limit configured. (Characters per line)
I will try to adapt the code to not exceed xxx chars per line.
