### ISSUE TITLE
Mailserver Fehler Cam #1: E06: Mailserver nicht konfiguriert

### ISSUE THREAD

**Issue by reifen01** [Woersty/LoxBerry-Plugin-cam-connect#39]
Cam #1: E06: Mailserver nicht konfiguriert aber Mailserver Testmail war erfolgreich?

lg Reinhard Fenzl

**Comment by Woersty** [comment]
Schau ich mir an.

**Comment by Scholleti** [comment]
Selbiges Problem bei mir. Hoffe auf ein baldiges release.

**Comment by Woersty** [comment]
Kann ich nicht nachvollziehen. Bei mir geht es. Bitte Log zusenden.
Welche Version verwendet ihr?
(Ich v2018.12.27)

**Comment by Scholleti** [comment]
Hier v2018.12.27. Log ist gesendet. Mail-Server ist korrekt konfiguriert. Testmails funktionieren. Bild bei klingeln funktioniert.

**Comment by elcid80** [comment]
Hallo, 

ich habe ebenfalls das Problem. Loxberry v1.4.2.2, CamConnect v2019.4.7. 
Mailserver ist konfiguriert und Testmail ist ok.

Auszug Logfile:
PHP: Cam #1: eMail ist not configured: SMTP.ISCONFIGURED is 0
ERROR: PHP: Cam #1: E06: Mailserver nicht konfiguriert
Ich sende das Logfile gleich zu.

VG
Martin

**Comment by Woersty** [comment]
@elcid80 ich habe dir mal per eMail geantwortet. Scheint ein Problem in der mail.json zu sein oder ich parse das falsch. Bekommen wir sicher hin, dürfte nix weltbewegendes sein.

**Comment by Woersty** [comment]
Auch nochmal für die anderen @Scholleti und @reifen01 :
Wie sieht eure \\<loxberry>\config\system\mail.json aus?

Speziell der Wert ISCONFIGURED ?

Beispiel von mir:
```
{
   "NOTIFICATION" : {
      "MAIL_PLUGIN_ERRORS" : "1",
      "MAIL_PLUGIN_INFOS" : "false",
      "MAIL_SYSTEM_ERRORS" : "1",
      "MAIL_SYSTEM_INFOS" : "1"
   },
   "SMTP" : {
      "ACTIVATE_MAIL" : 1,
      "AUTH" : 1,
      "CRYPT" : 1,
      "EMAIL" : "---@---.--",
      "ISCONFIGURED" : "1",
      "PORT" : "587",
      "SMTPPASS" : "---",
      "SMTPSERVER" : "---",
      "SMTPUSER" : "---"
   }
}
```

**Comment by Woersty** [comment]
Ich habe mal als Hotfix das PreRelease v2019.6.5. gebaut. 
Gehe dem aber mal nach.

**Comment by elcid80** [comment]
danke für die schnelle Analyse und Hotfix. 

Meine mail.json sieht wie folgt aus:

```
{
   "NOTIFICATION" : {
      "MAIL_PLUGIN_ERRORS" : "1",
      "MAIL_PLUGIN_INFOS" : "1",
      "MAIL_SYSTEM_ERRORS" : "true",
      "MAIL_SYSTEM_INFOS" : "true"
   },
   "SMTP" : {
      "ACTIVATE_MAIL" : 1,
      "AUTH" : 1,
      "CRYPT" : 1,
      "EMAIL" : „—@---.de",
      "ISCONFIGURED" : "0",
      "PORT" : "587",
      "SMTPPASS" : „---",
      "SMTPSERVER" : „---",
      "SMTPUSER" : „---"
   }
}

```
Der Fehler E06 tritt jetzt nicht mehr auf. 
Dafür habe ich leider einen anderen Fehler E10. 
Issue #43 hab ich gerade erstellt

**Comment by reifen01** [comment]
Dankeschön der Fehler Mailserver nicht konfiguriert ist jetzt weg👍🏻
