### ISSUE TITLE
Camera HIKAM A7 hinzufügen bitte

### ISSUE THREAD

**Issue by reifen01** [Woersty/LoxBerry-Plugin-cam-connect#40]
Wenn möglich die HiKam A7 in die Liste aufnehmen.
https://www.amazon.de/HiKam-%C3%9Cberwachungskamera-Personendetektion-Cloud-Speicherung-Datensicherheit/dp/B0782135T7

lg Reinhard Fenzl

**Comment by Woersty** [comment]
Ich benötige die Adresse des Standbildes der Kamera.
