### ISSUE TITLE
Keine Kamera zum auswählen 

### ISSUE THREAD

**Issue by wick0310** [Woersty/LoxBerry-Plugin-cam-connect#41]
Hallo bin gerade von alten Loxberry Version auf das neue umgestiegen und gerade am einrichten der Plugin .
Jetzt habe ich ein Problem nach der Installation wo alles erfolgreich war wenn ich das Plugin zum ersten Mal öffne kommt der erste Fehler " Ein Fehler ist Aufgetreten " Genereller Fehler 0 Keine Konfigurationsdatei gefunden . Ich versuche eine Standard   Konfigurationsdatei anzulegen .

Doch wenn ich dann das Plugin starte kommen keine Kameras zum Auswählen ?
Hoffe du kannst mir auch dieses Mal helfen 

Danke

**Comment by Woersty** [comment]
Richtig. Die Kamera muss mit "Kamera hinzufügen" angelegt werden.
