### ISSUE TITLE
E06: Mailserver nicht konfiguriert

### ISSUE THREAD

**Issue by OlliPe** [Woersty/LoxBerry-Plugin-cam-connect#42]
Mal wieder das selbe Problem.....
E06: Mailserver nicht konfiguriert .........auf schwarzem Hintergrund.

![image](https://user-images.githubusercontent.com/51337928/58826756-af169600-8641-11e9-82ef-66ddd8beff11.png)

Das hatte ich schonmal im Februar2019 und da habe ich das alte PlugIn vom letzen Herbst wieder installiert und der Fehler war weg.

Woran liegt es und wie kann ich das Plugin wieder zum Laufen ?

Hab mich so an die Funktionen gewöhnt .......

Gruß

**Comment by Woersty** [comment]
Die aktuelle Version vom Plugin ist installiert?
Eigentlich bezieht sich die Meldung auf die E-Mail Konfiguration vom LoxBerry selbst.
Ist die denn ok?

**Comment by Woersty** [comment]
#39

**Comment by Woersty** [comment]
Gelöst ab 2019.6.7
