### ISSUE TITLE
Unifi G3 Flex from Cloudkey gen2

### ISSUE THREAD

**Issue by s31teg** [Woersty/LoxBerry-Plugin-cam-connect#45]
Hello

The plugin does not seem to support g3 flex from the cloudkey gen2. The method documented is for the older NVR.

If you can help i can supply any info or remote access. 

S

**Comment by Woersty** [comment]
Sorry for the late reply.
All I need is the URL where we can grab the still image from.

BR C

**Comment by Woersty** [comment]
No response
