### ISSUE TITLE
E10: Bild zu klein

### ISSUE THREAD

**Issue by Oswald300** [Woersty/LoxBerry-Plugin-cam-connect#46]
Hallo,
ich bin von der Loxberry Version 0.2xx auf die neue Version v2.0.1.3 umgestiegen und habe die aktuelle Version 2019.10.20 von Cam-Connect-Plugin installiert. Ich habe das gleiche Kamera-Modell "Trendnet TV-IP310PI wie bei der v0.2..verwendet. Nach dem Test erhalte ich folgende Fehlermeldung:
E10: Bild zu klein
1<?xml version="1.0" encoding="iso-8859-l"?>
2<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
3        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
4<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
5 <head>
6  <title>404 - Not Found</title>
7 </head>
8 <body>
9 <h1>404 - Not Found</h1>
10 </body> 
ll</html>

Mit der letzten Version hat das bisher mehrere Jahre gut funktioniert. Mein String "Bild bei Klingeln"
war bisher: Loxberry/plugins/cam-connect/?kamera=Kamera-Hostname&port=80&user=Benutzername&pass=Passwort&cam-model=4
Meine Kamera ist eine EDIMAX IC-5150W.
Es wäre schön wenn Sie mir bei der Fehlerbeseitigung helfen könnten. Im Voraus vielen Dank

**Comment by Oswald300** [comment]
![grafik](https://user-images.githubusercontent.com/60741750/73941531-bd623380-48ed-11ea-9418-f56f68b0d10d.png)
Leider wurde die obige Fehlermeldung nicht richtig übernommen deshalb die Fehlermeldung als Bild.

**Comment by Woersty** [comment]
Das kann aber so nicht stimmen, weil Model 4 die Axis ist, wenn ich nicht irre.
Bitte nochmal prüfen, ob die Trendnet wirklich eingestellt ist.

**Comment by Woersty** [comment]
Übrigens kommt das 404 von der Seite, die aufgerufen wird.
Nicht vom Plugin. Also ist der URL definitiv falsch.

**Comment by Oswald300** [comment]
Hallo,
mit der Axis Kamera funktioniert "Bild bei klingeln" aber das Foto wird erst genau 20s nach dem Klingeln aufgenommen. Da ist dann der Besucher längst verschwunden bis das Foto ausgelöst wird.

**Comment by Woersty** [comment]
Gucke ich mir bei Gelegenheit mal an, woher die Verzögerung kommt.

**Comment by Oswald300** [comment]
Vielen Dank für die schnelle Hilfe!

**Comment by Woersty** [comment]
Ich habe das gerade nochmal probiert. Hier geht's. Habe aber nur eine AXIS Q1755 zum Testen.

**Comment by Woersty** [comment]
Keine Reaktion mehr erhalten.
