### ISSUE TITLE
Camera-Support-Request

### ISSUE THREAD

**Issue by Oswald300** [Woersty/LoxBerry-Plugin-cam-connect#47]
Ich habe eine Edimax IC-5150W Kamera und will sie benutzen

**Comment by Oswald300** [comment]
Bisher habe ich das Kameramodel Trendnet TV-IP310PI eingestellt und das hat mit der IC-5150W gut funktioniert aber seit ca. 3 Wochen werden keine Bilder in Loxone abgespeichert.
Ich hoffe es gibt für mein Problem eine Lösung.
MfG Oswald

**Comment by Woersty** [comment]
Fangen wir mal am Anfang an:
Was kommt, wenn du auf den Test Knopf drückst?
![image](https://user-images.githubusercontent.com/20454116/82039210-ee988f80-96a4-11ea-8493-bdad75e91df7.png)

**Comment by Oswald300** [comment]
![grafik](https://user-images.githubusercontent.com/60741750/82041550-a3807b80-96a8-11ea-939e-ad1f27a977d7.png)

**Comment by Oswald300** [comment]
![grafik](https://user-images.githubusercontent.com/60741750/82042109-9b750b80-96a9-11ea-9357-6d6b40a52f52.png)

**Comment by Woersty** [comment]
Dann kann das aber noch nie gegangen sein. Denn 404 not found heißt, dass es die aufgerufene Adresse nicht gibt. 
Die Definitionen stehen in der Datei \data\plugins\cam-connect\camera_models.dat
z.B. `1|Trendnet|TV-IP310PI|/Streaming/channels/1/picture|CURLAUTH_DIGEST`
Wenn du also die IP richtig hast solltest du bei <DeineIP>/Streaming/channels/1/picture ein Bild bekommen.
Wenn nicht, musst du mir den korrekten URL sagen, dann fügen wir ihn hinzu.
Viele Grüße

**Comment by Oswald300** [comment]
Hallo, 
vielen Dank für die schnelle Antwort, ich habe mit getäuscht, es war die Axis M3024-L Kamera. Wenn ich diese Kamera auswähle bekomme ich keine Fehlermeldung aber auch kein Bild. Wo kann man die URL der Kamera auslesen?
MfG Oswald

**Comment by Oswald300** [comment]
Mein Videostream funktioniert mit folgender Einstellung:
Benutzer:   http://PW@192.168.178.23/mjpg/1/video.mjpg

**Comment by Oswald300** [comment]
Korrektur:
URL Videostream  http://Benutzer:PW@192.168.178.23/mjpg/1/video.mjpg

**Comment by Oswald300** [comment]
Mit http://192.168.178.23/jpg/image.jpg bekomme ich im Browser Firefox ein Foto
MfG Oswald

**Comment by Woersty** [comment]
Ok, ich bau die Kamera mal dazu. Dann kannst probieren.

**Comment by Oswald300** [comment]
Funktioniert sehr gut. Vielen Dank für die Unterstützung.
MfG Oswald
