### ISSUE TITLE
Bildbearbeitung

### ISSUE THREAD

**Issue by ghost** [Woersty/LoxBerry-Plugin-cam-connect#5]
Hi, vielen Dank für dieses tolle Plugin! Wäre es möglich das Bild von der Auflösung her zu komprimieren? Bei 2000x2000 Pixel ist die Datei ziemlich groß. Ich nutze das Plugin auch um auf meinen Fritz Telefonen das Kamerabild anzuzeigen und bei der Dateigröße dauert es ziemlich lange bis über DECT das Bild übertragen wurde.

**Comment by Woersty** [comment]
Ist mir auch schon aufgefallen...
Was schwebt dir vor?
720px?

**Comment by ghost** [comment]
720px denke ich würde reichen. Für Smartphone und Tablet ausreichend und für das FritzFon allemal. Vielleicht kann man ja das als Option einfügen also: Vollauflösung oder reduziert 720px

**Comment by Woersty** [comment]
Ich werde ein Dropdown-Menü bauen denke ich. 👍🏻

**Comment by ghost** [comment]
Super! Vielen Dank für die super schnelle Umsetzung! Hab Version 1.3 jetzt mal ausprobiert. Er speichert bei mir nicht die Bildgröße in den Email Einstellungen (wenn ich das Plugin wieder öffne steht wieder unverändert drin) und es wäre super wenn das Bild auch nach dem Aufrufen der URL angepasst wird (die URL ist bei mir im FritzFon eingetragen für das Live Bild).

**Comment by Woersty** [comment]
Das mit dem Speichern macht er hier. Welchen Browser hast du? Ich schau nochmal. Bitte separaten Bug dafür melden. 

> und es wäre super wenn das Bild auch nach dem Aufrufen der URL angepasst wird (die URL ist bei mir im FritzFon eingetragen für das Live Bild).

Dann mache ich aber eine Option mit der man das beim Aufruf überschreiben kann - ähnlich email_to sonst ist es im Loxone auch so winzig. Ich pack das in die nächste Version mit rein.

**Comment by Woersty** [comment]
Wäre dann nicht auch ein Parameter sinnvoll um beim Aufruf keine eMail zu senden?

**Comment by ghost** [comment]
Mit der Option macht auf jeden fall sinn. Auch ein Parameter um keine Mail zu verschicken macht sinn. :-)
