### ISSUE TITLE
Bug: Bildbreite in der eMail:

### ISSUE THREAD

**Issue by ghost** [Woersty/LoxBerry-Plugin-cam-connect#7]
Hi,

wenn ich im Dropdown Menü (Bildbreite in der eMail:) eine Auflösung auswähle und speicher, dann ist nach erneuten aufrufen des Plugins die Einstellung zurück gesetzt auf "unverändert". Es wird auch das Bild per Mail in voller Auflösung verschickt (also nicht nur ein Anzeige Fehler)

Browser Safari unter MacOS und FireFox unter Win10. Plugin war vorher 1.2 und habe dann über die Pluginverwaltung 1.3 drüber installiert.

**Comment by Woersty** [comment]
Bitte nochmal mit Version 1.5 testen.

**Comment by ghost** [comment]
So hab es getestet. Und was soll ich sagen! Es klappt alles super!! Auflösung lässt sich richtig einstellen und bleibt gespeichert. Email wird in der richtigen Auflösung verschickt. Übergabe der Strings funktioniert! Kein Mailversand und Resize String habe ich getestet - 1A !!
Vielen Dank für deine Mühe!
